name: build

on: [push]

jobs:
  build-nodejs-shared-library-for-android:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node: [14.16.1]
        abi: [arm64, arm, x86_64, x86]

    steps:
      - uses: actions/checkout@v2

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
      - run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Setup dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update -y
          sudo apt install -y build-essential gcc-multilib g++-multilib

      - name: Build
        run: ANDROID_ABI=${{matrix.abi}} NODE_VERSION=${{matrix.node}} ./build-ci.sh

      - uses: actions/upload-artifact@v2
        with:
          name: libnode-android-v${{matrix.node}}-${{matrix.abi}}
          path: node-${{matrix.node}}/out/Release/share_library/*